name: grab-bestsellers
run-name: ${{ github.actor }} is grabbing bestsellers
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '11 5 * * *'
jobs:
  grab-bestsellers-list:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install ImageMagick
        run: apt update && apt install -y imagemagick
          
      - name: Go Get Dependencies
        run: go get && go mod tidy

      - name: Get fiction JSON
        run: wget -O combined-print-and-e-book-fiction.json https://api.nytimes.com/svc/books/v3/lists/current/combined-print-and-e-book-fiction.json?api-key=${{ secrets.NYT_API_KEY }}

      - name: Get nonfiction JSON
        run: wget -O combined-print-and-e-book-nonfiction.json https://api.nytimes.com/svc/books/v3/lists/current/combined-print-and-e-book-nonfiction.json?api-key=${{ secrets.NYT_API_KEY }}

      - name: Cache data
        run: go run main.go

      - name: Remove fiction JSON
        run: rm -f ./combined-print-and-e-book-fiction.json

      - name: Remove nonfiction JSON
        run: rm -f ./combined-print-and-e-book-nonfiction.json
        
      - name: Copy Images to min folder
        run: rsync -Rr ./img/ ./img/min/

      - name: Resize and Compress
        run: mogrify -path img/min -auto-orient -resize 150x150 -sampling-factor 4:2:0 -strip -quality 75 -interlace JPEG -colorspace RGB img/min/*.*

      # - name: Resize and Compress
      #   uses: pescew/ImageMagick-action/@debian
      #   with:
      #     command: mogrify -path img/min -auto-orient -resize 150x150 -sampling-factor 4:2:0 -strip -quality 75 -interlace JPEG -colorspace RGB img/min/*.*
  
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updating cache
          file_pattern: '*.json *.jpg *.jpeg *.png *.gif *.webp *.bmp *.jfif'        
